MVCPROJE/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAcessLayer.Concrete;
using EntityLayer.Concrete;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using PagedList.Mvc;
using BusinessLayer.Validation;
using FluentValidation.Results;
using FluentValidation;

namespace MVCPROJE.Controllers
{
    public class HeadingController : Controller
    {
        // GET: Heading
        HeadingManager headingManager = new HeadingManager(new HeadingRepository());
        CategoriManager categoriManager = new CategoriManager(new CategoriRepository());
        WriterManager writerManager = new WriterManager(new WriterRepository());
        ContentManager contentManager = new ContentManager(new ContentRepository());
        public ActionResult Index2()
        {
            var item = headingManager.GetList();
            
            return View(item);
        }
        public ActionResult Index(int p=1)
        {
            var item = headingManager.GetList().ToPagedList(p, 6);

            return View(item);

        }
        public ActionResult AddHeading()
        {

           
                List<SelectListItem> valuecategory = (from m in categoriManager.GetAllBL()
                                                      select new SelectListItem
                                                      {
                                                          Text = m.CategoryName,
                                                          Value = m.CategoryID.ToString()
                                                      }).ToList();
                List<SelectListItem> valuewriter = (from m in writerManager.GetList()
                                                    select new SelectListItem
                                                    {
                                                        Text = m.WriterName,
                                                        Value = m.WriterID.ToString()
                                                    }).ToList();
                ViewBag.Data = valuecategory;
                ViewBag.Writer = valuewriter;
            
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading heading) {
              
                heading.HeadingDate = DateTime.Parse(DateTime.Now.ToString());
                headingManager.HeadingAdd(heading);
                ViewBag.Status = true;
                return View();

        }
        public ActionResult ContentByHeading(int id)
        {
         var model=  contentManager.GetListByID(id);
            
            return View(model);
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {

            List<SelectListItem> valuecategory = (from m in categoriManager.GetAllBL()
                       select new SelectListItem
                       {
                           Text = m.CategoryName,
                           Value = m.CategoryID.ToString()
                       }).ToList();
            List<SelectListItem> Writers = (from m in writerManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = m.WriterName,
                                                      Value = m.WriterID.ToString()
                                                  }).ToList();
            ViewBag.Category = valuecategory;
            ViewBag.Writer = Writers;
            var model = headingManager.GetByID(id);
            return View(model);

        }
        [HttpPost]
        public ActionResult EditHeading(Heading heading)
        {
            //heading.HeadingStatus = true;
            headingManager.HeadingUpdate(heading);
          
            return RedirectToAction("Index");
        }



        [HttpGet]
        public ActionResult DeleteHeadingByStatus(int id)
        {

                var item = headingManager.GetByID(id);
                item.HeadingStatus = false;
                headingManager.HeadingDelete(item);
                return RedirectToAction("Index");
            
           
        }
        public ActionResult HeadingReport()
        {
            var list = headingManager.GetList();
            return View(list);
        }

    }
}

MVCPROJE/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Başlık Ekleme</h2>
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{

    <div class="form-group">
        @Html.Label("Başlık Adı Giriniz")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
    </div>

    <div class="form-group">
        @Html.Label("Kategori Adı Seçiniz")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.Data, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryID)
    </div>

    <div class="form-group">
        @Html.Label("Yazar Seçiniz")
        @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.Writer, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterID)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.HeadingStatus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.CheckBoxFor(model => model.HeadingStatus)
                @Html.ValidationMessageFor(model => model.HeadingStatus, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Başlık Oluştur" class="btn btn-primary" />
        </div>
    </div>
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@if (ViewBag.Status == true)
{
    <script>
        swal({
            title: "Bilgi",
            text: "Ekleme İşlemi başarılı",
            icon: "success",
            buttons: "Tamam"
        })
        setTimeout(yonlendir, 3000);
        function yonlendir() {
            location.assign("/Heading/Index");
        }
    </script>
}

MVCPROJE/Views/Heading/ContentByHeading.cshtml
@model IEnumerable<EntityLayer.Concrete.Content>
@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                @foreach (var item in Model)
                {
                    <!-- Timelime example  -->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- The time line -->
                            <div class="timeline">
                                <!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Writer.WriterName</a> @item.Writer.WriterSurname</h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>

                }
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MVCPROJE/Views/Heading/DeleteHeadingByStatus.cshtml
@{
    ViewBag.Title = "DeleteHeadingByStatus";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>DeleteHeadingByStatus</h2>

MVCPROJE/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>EditHeading</h2>
@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.HeadingID)
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })

        @Html.Label("Başlık Tarihi")
        <br />
        @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Seçiniz")
        @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.Writer)
        <br />
        @Html.Label("Kategori Seçiniz")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.Category)
        <div class="form-group">
            @Html.Label("Durum")
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.HeadingStatus)
                    @Html.ValidationMessageFor(model => model.HeadingStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <button class="btn btn-primary" type="submit" value="Güncelle">Güncelle</button>
    </div>
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@if (ViewBag.Status == true)
{
    <script>
        swal({
            title: "Bilgi",
            text: "Günceleme İşlemi başarılı",
            icon: "success",
            buttons: "Tamam"
        })
        setTimeout(yonlendir, 3000);
        function yonlendir() {
            location.assign("/Heading/Index");
        }
    </script>
}

MVCPROJE/Views/Heading/HeadingReport.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get In Excel, PDF, CSV Format</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>Başlık ID</th>
                <th>Başlık Adı</th>
                <th>Tarih</th>
                <th>Yazar Adı Ve Soyadı</th>
                <th>Yazar Mail</th>
                <th>Yazar Başlık</th>
                <th>HeadingID</th>
                <th>Durum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.HeadingID</td>
                    <td>@x.HeadingName</td>
                    <td>@x.HeadingDate</td>
                    <td>@x.Writer.WriterName @x.Writer.WriterSurname</td>
                    <td>@x.Writer.WriterMail</td>
                    <td>@x.Writer.WriterTitle</td>
                    <td>@x.HeadingID</td>
                    <td>@x.HeadingStatus</td>

                </tr>
            }

        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
	$(document).ready(function() {
	    var table = $('#example').DataTable( {
	        lengthChange: false,
	        buttons: [ 'copy', 'excel', 'csv', 'pdf', 'colvis' ]
	    } );

	    table.buttons().container()
	        .appendTo( '#example_wrapper .col-md-6:eq(0)' );
	} );
    </script>
</body>
</html>

MVCPROJE/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model PagedList.IPagedList<Heading>
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<body class="hold-transition sidebar-mini">

    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlıklar</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                ID
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 10%">
                                Tarih
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 5%">
                                Resim
                            </th>
                            <th>Durum</th>
                        </tr>
                    </thead>
                    <tbody>


                        @foreach (var item in Model)
                        {


                            <tr>


                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    @item.HeadingName
                                </td>
                                <td>
                                    <a>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </a>

                                </td>
                                <td class="project-state">
                                    <span class="badge badge-warning">@item.Category.CategoryName</span>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img src="~/MvcProjeKampiTema-main/MvcProjeKampiTema-main/Mvc Proje Kampı Tema/AdminLTE-3.0.4/dist/img/avatar.png" style="width:50px;height:50px" />

                                        </li>
                                    </ul>
                                </td>
                                <td>@item.HeadingStatus</td>
                                @*<td class="project-state">
                                        <span class="badge badge-success">Success</span>
                                    </td>*@
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Heading/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        yazılar(içerik mesajlar)
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeadingByStatus/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                       Pasif Yap
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
</body>
@Html.PagedListPager((IPagedList)Model, p => Url.Action("AllHeading", new { p }), new PagedListRenderOptions
{
  LiElementClasses=new List<string>
  {
      "page-link"
  }

})
<a href="/Heading/AddHeading" class="btn btn-primary">Yeni başlık ekle</a>

MVCPROJE/Views/Heading/Index2.cshtml
@model IEnumerable<EntityLayer.Concrete.Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Baslık</th>
        <th>Tarih</th>
        <th> Categori Adı</th>
        <th>Yazar Adı</th>
       
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.HeadingID</td>
            <td>@item.HeadingName</td>
            <td>@item.HeadingDate</td>
            <td>@item.Category.CategoryName</td>
            <td>@item.Writer.WriterName</td>
            <td><a href="/Writer/WriterDelete/@item.CategoryID" class="btn btn-danger">Sil</a></td>
            <td><a href="/writer/WriterUpdate/@item.CategoryID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="" class="btn btn-warning">Başlıklar</a></td>

        </tr>
    }
</table>