MVCPROJE/Controllers/ChartTestController.cs
using MVCPROJE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCPROJE.Controllers
{
    public class ChartTestController : Controller
    {
        // GET: ChartTest


        public ActionResult Index()
        {
            return View();
        }
        public JsonResult CategoryChart()
        {

            return Json(BlogList().ToList(), JsonRequestBehavior.AllowGet);
        }


        public List<CategoryClass> BlogList()
        {
            List<CategoryClass> lst = new List<CategoryClass>();
            lst.Add(new CategoryClass()
            {
                CategoryName = "Yazılım",
                CategoryCount = 8

            });
            lst.Add(new CategoryClass()
            {
                CategoryName = "Yazılım",
                CategoryCount = 8

            });
            lst.Add(new CategoryClass()
            {
                CategoryName = "VeriTabanı",
                CategoryCount = 4

            });
            lst.Add(new CategoryClass()
            {
                CategoryName = "Web",
                CategoryCount = 5

            });
            lst.Add(new CategoryClass()
            {
                CategoryName = "İngilizce",
                CategoryCount = 5

            });

            return lst;

        }

    }
}

MVCPROJE/Views/ChartTest/Index.cshtml
@{
    Layout = null;
}

<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</head>
<body>
    <h1>index</h1>
    <div id="Piechart_div"></div>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryChart", "ChartTest")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Category Name');
            data.addColumn('number', 'Category Count');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.CategoryCount]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</body>
</html>